In [3]:
nums = [3, 5, 7, 8, 12]
cubes = [x**3 for x in nums]
print(cubes)

[27, 125, 343, 512, 1728]


In [5]:
my_dict = {}

my_dict['parrot'] = 2
my_dict['goat'] = 4
my_dict['spider'] = 8
my_dict['crab'] = 10

print(my_dict)

{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


In [7]:
my_dict = {'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}

total_legs = 0

for animal, legs in my_dict.items():
    print(f'The {animal} has {legs} legs.')
    total_legs += legs

print(f'The total number of legs is: {total_legs}')

The parrot has 2 legs.
The goat has 4 legs.
The spider has 8 legs.
The crab has 10 legs.
The total number of legs is: 24


In [9]:
A = (3, 9, 4, [5, 6])

A[3][0] = 8

print(A)

(3, 9, 4, [8, 6])


In [11]:
A = (3, 9, 4, [5, 6])
del A

In [13]:
B = ('a', 'p', 'p', 'l', 'e')

count_p = B.count('p')

print(f"The number of occurrences of 'p' in the tuple is: {count_p}")

The number of occurrences of 'p' in the tuple is: 2


In [15]:
B = ('a', 'p', 'p', 'l', 'e')

index_l = B.index('l')

print(f"The index of 'l' in the tuple is: {index_l}")

The index of 'l' in the tuple is: 3


In [17]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

z = np.array([1, 0, 1])

print("Matrix A:")
print(A)
print("\nArray z:")
print(z)

Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array z:
[1 0 1]


In [42]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = A[:2, :2]

print("Subarray b:")
print(b)

Subarray b:
[[1 2]
 [5 6]]


In [44]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

C = np.empty_like(A)

print("Matrix C:")
print(C)

Matrix C:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
import numpy as np

# Define matrix A
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Define vector z
z = np.array([1, 0, 1])

# Initialize matrix C with the same shape as A
C = np.empty_like(A)

# Add vector z to each column of matrix A using an explicit loop
for i in range(A.shape[1]):  # Loop over each column
    C[:, i] = A[:, i] + z

# Print the result
print("Matrix C after adding vector z to each column of A:")
print(C)

Matrix C after adding vector z to each column of A:
[[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]


In [48]:
import numpy as np

X = np.array([[1, 2],
              [3, 4]])

Y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])

print("Matrix X:")
print(X)

print("\nMatrix Y:")
print(Y)

print("\nVector v:")
print(v)

Matrix X:
[[1 2]
 [3 4]]

Matrix Y:
[[5 6]
 [7 8]]

Vector v:
[ 9 10]


In [50]:
result = X + Y
print("Sum of Matrix X and Y:")
print(result)

Sum of Matrix X and Y:
[[ 6  8]
 [10 12]]


In [52]:
result = X @ Y
print("Product of Matrix X and Y:")
print(result)

Product of Matrix X and Y:
[[19 22]
 [43 50]]


In [54]:
sqrt_Y = np.sqrt(Y)
print("Element-wise square root of matrix Y:")
print(sqrt_Y)

Element-wise square root of matrix Y:
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [56]:
result = np.dot(X, v)
print("Dot product of matrix X and vector v:")
print(result)

Dot product of matrix X and vector v:
[29 67]


In [58]:
column_sums = np.sum(X, axis=0)
print("Sum of each column in X:")
print(column_sums)

Sum of each column in X:
[4 6]


In [10]:
def Compute(distance, time):
    if time == 0:
        raise ValueError("Time cannot be zero, as it would lead to division by zero.")
    velocity = distance / time
    return velocity
distance = 330.0
time = 90.0
velocity = Compute(distance, time)
print({velocity})

{3.6666666666666665}


In [18]:
even_num = [x for x in range(2, 13, 2)]
def mult(numbers):
    product = 1
    for number in numbers:
        product *= number
    return product
product_of_even_nums = mult(even_num)
print("List of even numbers up to 12:")
print(even_num)
print("\nProduct of all entries in the list:")
print(product_of_even_nums)

List of even numbers up to 12:
[2, 4, 6, 8, 10, 12]

Product of all entries in the list:
46080


In [20]:
import pandas as pd

data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

print("First two rows of the DataFrame:")
print(df.head(2))

First two rows of the DataFrame:
   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [26]:
import pandas as pd

# Create the DataFrame with the specified data
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Print the second column (C2)
print("Second column of the DataFrame:")
print(df['C2'])

Second column of the DataFrame:
0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [28]:
df.rename(columns={'C3': 'B3'}, inplace=True)

print("DataFrame with renamed column:")
print(df)

DataFrame with renamed column:
   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [30]:
df['Sum'] = df.sum(axis=1)

print("DataFrame with the new 'Sum' column:")
print(df)

DataFrame with the new 'Sum' column:
   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [72]:
import pandas as pd

# Create the DataFrame with the specified data
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'B3': [7, 9, 8, 6, 5],  # Column name changed from C3 to B3
    'C4': [7, 5, 2, 8, 8]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Calculate the sum of each row and add it as a new column named 'Sum'
df['Sum'] = df.sum(axis=1)

# Print the DataFrame to see the changes
print("DataFrame with the new 'Sum' column:")
print(df)

DataFrame with the new 'Sum' column:
   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [54]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('C:\\Users\\maham\\Downloads\\hello_sample.csv')


# Print the DataFrame to check its contents
print("DataFrame loaded from 'hello_sample.csv':")
print(df)

DataFrame loaded from 'hello_sample.csv':
    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       6

In [56]:
print("Bottom 2 records of the DataFrame:")
print(df.tail(2))

Bottom 2 records of the DataFrame:
   Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


In [58]:
print("Information about the DataFrame:")
df.info()

Information about the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 868.0+ bytes


In [60]:
print("Shape of the DataFrame (rows x columns):")
print(df.shape)

Shape of the DataFrame (rows x columns):
(23, 4)


In [62]:
sorted_df = df.sort_values(by='Weight')

print("DataFrame sorted by 'Weight':")
print(sorted_df)

DataFrame sorted by 'Weight':
    Gender  F_Color     B_Month  Weight
2     Male    Black     October      53
16    Male    Black      August      54
9     Male     Blue         May      58
7   Female      Red   September      59
18    Male  Mustard   December       60
10  Female      Red    October       60
6     Male   Orange      August      60
8     Male     Blue        July      60
3   Female     Blue    February      63
11    Male    Black   September      65
22    Male      Red  September       66
20    Male    Black   February       67
13    Male    Black       April      72
1     Male      Red       March      72
21    Male   Yellow       April      74
19  Female    Black    October       76
0     Male    Black       March      77
4     Male    black    October       80
17    Male    Black     January      82
12    Male    Green    December      85
14    Male    Green    January       90
15    Male   Yellow   November       90
5   Female    Black    december      97


In [64]:
print("Missing values in the DataFrame (True indicates missing values):")
print(df.isnull())

# Use dropna() to remove rows with any missing values
df_dropped_rows = df.dropna()
# Print the DataFrame after dropping rows with missing values
print("\nDataFrame after dropping rows with missing values:")
print(df_dropped_rows)

# Use dropna() to remove columns with any missing values
df_dropped_columns = df.dropna(axis=1)
# Print the DataFrame after dropping columns with missing values
print("\nDataFrame after dropping columns with missing values:")
print(df_dropped_columns)

Missing values in the DataFrame (True indicates missing values):
    Gender  F_Color  B_Month  Weight
0    False    False    False   False
1    False    False    False   False
2    False    False    False   False
3    False    False    False   False
4    False    False    False   False
5    False    False    False   False
6    False    False    False   False
7    False    False    False   False
8    False    False    False   False
9    False    False    False   False
10   False    False    False   False
11   False    False    False   False
12   False    False    False   False
13   False    False    False   False
14   False    False    False   False
15   False    False    False   False
16   False    False    False   False
17   False    False    False   False
18   False    False    False   False
19   False    False    False   False
20   False    False    False   False
21   False    False    False   False
22   False    False    False   False

DataFrame after dropping rows with missing val